### ISSUE TITLE
Rendering jsreports from node js

### ISSUE THREAD

**Issue by Sunil-Revankar** [jsreport/nodejs-client#4]
These are the steps I am following:
1. I have started jsreports server on the port 5488, where I have created template in the same environment (jsreports studio).

2. I have started nodejs server in 3000 port, where I have server.js file which contains following code

var http = require("http");
http.createServer(function (req, res){
Var client = require ("jsreport-client")("url");
client.render({
template:{shortid: "", engine: "", recipe: ""},
Data: {}
}, function (err, resp){
res.Stream.pipe(resp);
});
}).Listen(3000);

Here I couldn't able to generate the report, can I get an help to solve this.

In the above code I am passing json data with template

**Comment by Sunil-Revankar** [comment]
For the this execution I am getting console errors as follows:
1. Cannot read property 'pipe' of undefined
2. Cannot read property 'stream' of undefined
3. If I replace the code "res.Stream.pipe(resp);" with console.log(), the error msg wat I am getting is, "Error: Unknown error, status code 404"

**Comment by pofider** [comment]
what is the url you pass here?

` require ("jsreport-client")("url");`

**Comment by Sunil-Revankar** [comment]
require ("jsreport-client")("http://localhost:5488/api/report");

This is where my template is available

**Comment by pofider** [comment]
It should be without `api/report` because it is being add automatically

https://github.com/jsreport/nodejs-client/blob/master/lib/client.js#L34

**Comment by Sunil-Revankar** [comment]
Even this I tried, it doesn't make any change

**Comment by pofider** [comment]
Please paste the minimal exact code which returns 404.

**Comment by Sunil-Revankar** [comment]
Ok, I'll post that error.
Before that can u let me know where should I need to paste this part of code in the "client.js" file of lib folder

{"scripts": {"allowedModules": ["request"]}}

**Comment by pofider** [comment]
This is server configuration. So it should be in `dev|prod.config.json` at the jsreport server.

**Comment by Sunil-Revankar** [comment]
The issue was at this code itself
require ("jsreport-client")("http://localhost:5488/api/report");

I am able to get the report now, after changing the URL as you said.

Thank you very much @pofider

**Comment by Sunil-Revankar** [comment]
@pofider Could you help on the below mentioned code to render my custom template in the jsreport
`exports.renderReport_ICE = function(req, res){
	var templateName = req.body.templateName;
	jsreport.render({
		template: {
			content: templateName,
			recipe: 'html',
			engine: 'none'
		}
	}).then(function(o) {
		o.result.pipe(res)
	}).catch(function(e) {
		console.error(e)
	})
}`

Here i am passing the file name of custom template in the content section but i got error message like this
ypeError: Cannot read property 'render' of undefined
    at exports.renderReport_ICE (d:\git\Ninteen68_Ver2.0_Express\server\controllers\report.js:14:19)
    at Layer.handle [as handle_request] (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\layer.js:95:5)
    at d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:330:12)
    at next (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:271:10)
    at logger (d:\git\Ninteen68_Ver2.0_Express\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:312:13)
    at d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:330:12)
    at next (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (d:\git\Ninteen68_Ver2.0_Express\node_modules\body-parser\lib\types\urlencoded.js:82:7)
    at Layer.handle [as handle_request] (d:\git\Ninteen68_Ver2.0_Express\node_modules\express\lib\router\layer.js:95:5)

**Comment by Sunil-Revankar** [comment]
`exports.renderReport_ICE = function(req, res){`
`jsreport.render({ `
`template: { content: templateName, recipe: 'html', engine: 'none' }`
` }).then(function(o) { o.result.pipe(res)`
`}).catch(function(e) { console.error(e) }) }`
